import Header from "./Header";
import "./globals.css";
import { Preahvihear } from "next/font/google";

const inter = Preahvihear({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      <div className={inter.className}>
        <Header />
      </div>

      <div className={inter.className}>{children}</div>
    </div>
  );
}
